name: Xcode - Build And Analyze On Develop

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
           pod install --repo-update --clean-install --project-directory=Thirty/
           xcodebuild clean test -workspace Thirty/Thirty.xcworkspace -scheme Thirty -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
        
